#!/usr/bin/env python3
"""Export phone launcher assets from app/assets/icon/house.svg."""

import argparse
from copy import deepcopy
from io import BytesIO
import json
import math
from pathlib import Path
import xml.etree.ElementTree as ET

from PIL import Image, ImageChops, ImageDraw
import resvg_py


ROOT = Path(__file__).resolve().parents[1]
MASTER = ROOT / "app/assets/icon/house.svg"
RES = ROOT / "app/android/app/src/main/res"
IOS = ROOT / "app/ios/Runner/Assets.xcassets/AppIcon.appiconset"
SVG = "{http://www.w3.org/2000/svg}"
ET.register_namespace("", SVG[1:-1])


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def render(master, size, foreground=False):
    root = deepcopy(master)
    if foreground:
        root.remove(root.find(f"{SVG}rect"))
    # Android displays the central 72dp of the 108dp adaptive layers.
    root.set("viewBox", "18 18 72 72")
    root.set("width", str(size))
    root.set("height", str(size))
    png = resvg_py.svg_to_bytes(svg_string=ET.tostring(root, encoding="unicode"))
    return Image.open(BytesIO(png)).convert("RGBA" if foreground else "RGB")


def vector(master, monochrome=False):
    group = master.find(f"{SVG}g")
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by scripts/generate_icons.py; edit house.svg. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp" android:height="108dp"',
        '    android:viewportWidth="108" android:viewportHeight="108">',
    ]
    for path in group:
        if path.tag != f"{SVG}path":
            raise ValueError("Launcher master supports path elements only")
        color = "#FFFFFF" if monochrome else group.attrib["stroke"]
        lines.extend([
            '    <path android:fillColor="@android:color/transparent"',
            f'        android:strokeColor="{color}"',
            f'        android:strokeWidth="{path.attrib["stroke-width"]}"',
            f'        android:strokeLineCap="{group.attrib["stroke-linecap"]}"',
            f'        android:strokeLineJoin="{group.attrib["stroke-linejoin"]}"',
            f'        android:pathData="{path.attrib["d"]}" />',
        ])
    return "\n".join(lines + ["</vector>", ""])


def preview(master, target):
    """Synthetic mask/readability sheet; contains no device or private data."""
    scale = 4
    sheet = Image.new("RGB", (800, 400), "#EDF0EA")
    draw = ImageDraw.Draw(sheet)
    foreground = render(master, 128 * scale, foreground=True)
    # Verify the entire mark fits Android's central 66dp safe circle.
    safe = Image.new("L", foreground.size)
    safe_draw = ImageDraw.Draw(safe)
    inset = foreground.width * 3 / 72
    safe_draw.ellipse((inset, inset, foreground.width - inset, foreground.height - inset), fill=255)
    if ImageChops.subtract(foreground.getchannel("A"), safe).getbbox():
        raise ValueError("House extends outside the Android safe circle")
    for i, label in enumerate(("Circle", "Rounded square", "Squircle", "Themed")):
        icon = render(master, 128 * scale)
        mask = Image.new("L", icon.size)
        d = ImageDraw.Draw(mask)
        bounds = (0, 0, icon.width - 1, icon.height - 1)
        if i in (0, 3):
            d.ellipse(bounds, fill=255)
        elif i == 1:
            d.rounded_rectangle(bounds, radius=icon.width * .22, fill=255)
        else:
            # Superellipse x^4 + y^4 = r^4.
            center = (icon.width - 1) / 2
            points = []
            for degree in range(360):
                t = math.radians(degree)
                x, y = math.cos(t), math.sin(t)
                points.append((center + center * math.copysign(abs(x) ** .5, x),
                               center + center * math.copysign(abs(y) ** .5, y)))
            d.polygon(points, fill=255)
        if i == 3:
            icon = Image.new("RGB", icon.size, "#D0E8D8")
            icon.paste("#173B2B", (0, 0, icon.width, icon.height), foreground.getchannel("A"))
        x = 36 + i * 196
        sheet.paste(icon.resize((128, 128), Image.Resampling.LANCZOS), (x, 40),
                    mask.resize((128, 128), Image.Resampling.LANCZOS))
        draw.text((x, 185), label, fill="#173B2B")
    draw.text((36, 240), "Actual pixel sizes: 20 / 29 / 40 / 48 / 60", fill="#173B2B")
    x = 36
    for size in (20, 29, 40, 48, 60):
        sheet.paste(render(master, size), (x, 275))
        draw.text((x, 345), str(size), fill="#173B2B")
        x += size + 35
    target.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(target)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview", type=Path, help="Also write a mask/readability sheet")
    args = parser.parse_args()
    master = ET.parse(MASTER).getroot()
    for density, size in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        target = RES / f"mipmap-{density}/ic_launcher.png"
        target.parent.mkdir(parents=True, exist_ok=True)
        render(master, size).save(target)
    write(RES / "drawable/ic_launcher_foreground.xml", vector(master))
    write(RES / "drawable/ic_launcher_monochrome.xml", vector(master, monochrome=True))
    color = master.find(f"{SVG}rect").attrib["fill"]
    write(RES / "values/ic_launcher_colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icons.py; edit house.svg. -->
<resources>
    <color name="ic_launcher_background">{color}</color>
</resources>
''')
    for api in (26, 33):
        mono = '\n    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />' if api == 33 else ""
        write(RES / f"mipmap-anydpi-v{api}/ic_launcher.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icons.py; edit house.svg. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />{mono}
</adaptive-icon>
''')
    for item in json.loads((IOS / "Contents.json").read_text())["images"]:
        size = float(item["size"].split("x")[0]) * float(item["scale"].removesuffix("x"))
        render(master, int(size)).save(IOS / item["filename"])
    render(master, 1024).save(MASTER.with_name("house.png"))
    if args.preview:
        preview(master, args.preview)
    print("Generated Android legacy/adaptive/themed icons and all iOS catalog sizes.")


if __name__ == "__main__":
    main()
